### ISSUE TITLE
Feedback on the App

### ISSUE THREAD

**Issue by jomefavourite** [phavour-codes/Quiz-App#1]
Hello Favour!

After going through your JS code, I must say I really like how you broke everything down into chunks of functions. Good job 👍

Okay, so as for the things you could improve on is that there's no way to keep track of the user score. I know it could be challenging but do give it a shot, try keeping track of the user score.

Here's something I noticed you could also try fixing, it's not really a bug now. But I feel it's better for a user not be able to change the background. To fix this, the button should only be clicked once.

https://user-images.githubusercontent.com/54733225/162192307-156876e1-516d-4ffb-ac11-e8269b25946f.mp4

I also noticed you had the questions in your JS file directly, could you turn the questions array to JSON data and try to make an asynchronous call to the questions data using the `fetch()` method.

> This isn't necessary but it would help you practice how to use an API endpoint.

I guess that's all, good job by the way  👍

**Comment by phavour-codes** [comment]
Thank you sir. God bless you

**Comment by jomefavourite** [comment]
You're very much welcome 😊
